name: branch-check

on:
  push:
    branches:
      - '*'
  pull_request:
    types: [opened, synchronize, edited, reopened]
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: ['3.6', '3.7', '3.8', '3.9']

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: Dependencies
        run: pip install .

      - name: Get Version
        run: echo "VERSION=$(python setup.py version | tail -n1).${{ github.sha }}" >> $GITHUB_ENV

      - name: Test
        run: python setup.py coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.organization=kronenthaler
            -Dsonar.projectKey=kronenthaler_mod-pbxproj
            -Dsonar.projectName=mod-pbxproj
            -Dsonar.projectVersion=${{ env.VERSION }}
            -Dsonar.python.coverage.reportPaths=tests/coverage.xml
            -Dsonar.sources=.
            -Dsonar.tests=tests/
            -Dsonar.verbose=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Codacy
        if: github.event_name != 'pull_request'
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: tests/coverage.xml
