name: publish

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Dependencies
        run: |
          pip install .
          pip install setuptools wheel twine

      - name: Deploy
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
